/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRecommendedDictionariesRouteImport } from './routes/api/recommended-dictionaries'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSearchSuggestionsRouteImport } from './routes/api/search/suggestions'
import { Route as ApiMediaStreamVideoIdRouteImport } from './routes/api/media/stream/$videoId'
import { Route as ApiMediaDownloadVideoIdRouteImport } from './routes/api/media/download/$videoId'
import { Route as ApiLyricsTrackSpotifyTrackIdRouteImport } from './routes/api/lyrics/track/$spotifyTrackId'
import { Route as ApiLyricsMatchVideoIdRouteImport } from './routes/api/lyrics/match/$videoId'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendedDictionariesRoute =
  ApiRecommendedDictionariesRouteImport.update({
    id: '/api/recommended-dictionaries',
    path: '/api/recommended-dictionaries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchSuggestionsRoute = ApiSearchSuggestionsRouteImport.update({
  id: '/api/search/suggestions',
  path: '/api/search/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaStreamVideoIdRoute = ApiMediaStreamVideoIdRouteImport.update({
  id: '/api/media/stream/$videoId',
  path: '/api/media/stream/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaDownloadVideoIdRoute = ApiMediaDownloadVideoIdRouteImport.update({
  id: '/api/media/download/$videoId',
  path: '/api/media/download/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricsTrackSpotifyTrackIdRoute =
  ApiLyricsTrackSpotifyTrackIdRouteImport.update({
    id: '/api/lyrics/track/$spotifyTrackId',
    path: '/api/lyrics/track/$spotifyTrackId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLyricsMatchVideoIdRoute = ApiLyricsMatchVideoIdRouteImport.update({
  id: '/api/lyrics/match/$videoId',
  path: '/api/lyrics/match/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/watch': typeof WatchRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recommended-dictionaries': typeof ApiRecommendedDictionariesRoute
  '/api/search/suggestions': typeof ApiSearchSuggestionsRoute
  '/api/lyrics/match/$videoId': typeof ApiLyricsMatchVideoIdRoute
  '/api/lyrics/track/$spotifyTrackId': typeof ApiLyricsTrackSpotifyTrackIdRoute
  '/api/media/download/$videoId': typeof ApiMediaDownloadVideoIdRoute
  '/api/media/stream/$videoId': typeof ApiMediaStreamVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/watch': typeof WatchRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recommended-dictionaries': typeof ApiRecommendedDictionariesRoute
  '/api/search/suggestions': typeof ApiSearchSuggestionsRoute
  '/api/lyrics/match/$videoId': typeof ApiLyricsMatchVideoIdRoute
  '/api/lyrics/track/$spotifyTrackId': typeof ApiLyricsTrackSpotifyTrackIdRoute
  '/api/media/download/$videoId': typeof ApiMediaDownloadVideoIdRoute
  '/api/media/stream/$videoId': typeof ApiMediaStreamVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/watch': typeof WatchRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recommended-dictionaries': typeof ApiRecommendedDictionariesRoute
  '/api/search/suggestions': typeof ApiSearchSuggestionsRoute
  '/api/lyrics/match/$videoId': typeof ApiLyricsMatchVideoIdRoute
  '/api/lyrics/track/$spotifyTrackId': typeof ApiLyricsTrackSpotifyTrackIdRoute
  '/api/media/download/$videoId': typeof ApiMediaDownloadVideoIdRoute
  '/api/media/stream/$videoId': typeof ApiMediaStreamVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/watch'
    | '/api/health'
    | '/api/recommended-dictionaries'
    | '/api/search/suggestions'
    | '/api/lyrics/match/$videoId'
    | '/api/lyrics/track/$spotifyTrackId'
    | '/api/media/download/$videoId'
    | '/api/media/stream/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/watch'
    | '/api/health'
    | '/api/recommended-dictionaries'
    | '/api/search/suggestions'
    | '/api/lyrics/match/$videoId'
    | '/api/lyrics/track/$spotifyTrackId'
    | '/api/media/download/$videoId'
    | '/api/media/stream/$videoId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/watch'
    | '/api/health'
    | '/api/recommended-dictionaries'
    | '/api/search/suggestions'
    | '/api/lyrics/match/$videoId'
    | '/api/lyrics/track/$spotifyTrackId'
    | '/api/media/download/$videoId'
    | '/api/media/stream/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  WatchRoute: typeof WatchRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecommendedDictionariesRoute: typeof ApiRecommendedDictionariesRoute
  ApiSearchSuggestionsRoute: typeof ApiSearchSuggestionsRoute
  ApiLyricsMatchVideoIdRoute: typeof ApiLyricsMatchVideoIdRoute
  ApiLyricsTrackSpotifyTrackIdRoute: typeof ApiLyricsTrackSpotifyTrackIdRoute
  ApiMediaDownloadVideoIdRoute: typeof ApiMediaDownloadVideoIdRoute
  ApiMediaStreamVideoIdRoute: typeof ApiMediaStreamVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommended-dictionaries': {
      id: '/api/recommended-dictionaries'
      path: '/api/recommended-dictionaries'
      fullPath: '/api/recommended-dictionaries'
      preLoaderRoute: typeof ApiRecommendedDictionariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/suggestions': {
      id: '/api/search/suggestions'
      path: '/api/search/suggestions'
      fullPath: '/api/search/suggestions'
      preLoaderRoute: typeof ApiSearchSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/stream/$videoId': {
      id: '/api/media/stream/$videoId'
      path: '/api/media/stream/$videoId'
      fullPath: '/api/media/stream/$videoId'
      preLoaderRoute: typeof ApiMediaStreamVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/download/$videoId': {
      id: '/api/media/download/$videoId'
      path: '/api/media/download/$videoId'
      fullPath: '/api/media/download/$videoId'
      preLoaderRoute: typeof ApiMediaDownloadVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics/track/$spotifyTrackId': {
      id: '/api/lyrics/track/$spotifyTrackId'
      path: '/api/lyrics/track/$spotifyTrackId'
      fullPath: '/api/lyrics/track/$spotifyTrackId'
      preLoaderRoute: typeof ApiLyricsTrackSpotifyTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics/match/$videoId': {
      id: '/api/lyrics/match/$videoId'
      path: '/api/lyrics/match/$videoId'
      fullPath: '/api/lyrics/match/$videoId'
      preLoaderRoute: typeof ApiLyricsMatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  WatchRoute: WatchRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecommendedDictionariesRoute: ApiRecommendedDictionariesRoute,
  ApiSearchSuggestionsRoute: ApiSearchSuggestionsRoute,
  ApiLyricsMatchVideoIdRoute: ApiLyricsMatchVideoIdRoute,
  ApiLyricsTrackSpotifyTrackIdRoute: ApiLyricsTrackSpotifyTrackIdRoute,
  ApiMediaDownloadVideoIdRoute: ApiMediaDownloadVideoIdRoute,
  ApiMediaStreamVideoIdRoute: ApiMediaStreamVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
